server:
  ip_address: "0.0.0.0"
  port: "8003"
  saved_data_path: "result"
parameter:
  embeddings_name: "sentence-transformers/all-MiniLM-L6-v2"

  DATA_PATH: "data/"
  DB_FAISS_PATH: "vectorstore/db_faiss"
  DB_MESSAGES: "db_messages/"

  # Số đoạn sẽ được thêm vào lời nhắc. Quá nhiều đoạn trích và bạn có nguy cơ bị cả lời nhắc vượt qua
  # giới hạn mã thông báo và mô hình không thể tìm thấy câu trả lời chính xác
  prompt_number_snippets: 10

  # GPT related constants
  gpt_model_to_use: "gpt-3.5-turbo-16k"

  temperature: 0
  gpt_max_tokens: 1000

  # Số tin nhắn của người dùng trước đây sẽ được sử dụng để tìm kiếm các đoạn có liên quan
  search_number_messages: 3

  # PDF Chunking constants
  chunk_size: 1024
  chunk_overlap: 64

  # Số đoạn trích được FAISS truy xuất
  number_snippets_to_retrieve: 10


yolo_params:
  weight_path: "weight/best.pt"
  classes: {0: 'Bàn chải điện', 1: 'Bình đun nước', 2: 'Đèn Năng Lượng Mặt Trời', 3: 'Điều hòa', 4: 'Ghế massage daikiosan', 5: 'Máy cạo râu', 6: 'Máy Giặt', 7: 'Máy sấy tóc', 8: 'Máy xay', 9: 'Nồi áp suất', 10: 'Nồi cơm điện', 11: 'Robot hút bụi', 12: 'Thiết bị Camera', 13: 'Thiết bị Wifi', 14: 'Bàn là', 15: 'Bếp từ', 16: 'Bình nước nóng', 17: 'lò nướng', 18: 'Lò vi sóng', 19: 'Máy đánh trứng', 20: 'Máy ép', 21: 'Máy hút bụi', 22: 'Máy lọc không khí', 23: 'Máy lọc nước', 24: 'Nồi chiên không dầu', 25: 'Thiết bị Webcam'}